name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Configure kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Blue-Green Deployment
      run: |
        kubectl apply -f kubernetes/
        kubectl rollout status deployment/account-service
        kubectl rollout status deployment/api-gateway
        kubectl rollout status deployment/notification-service
        kubectl rollout status deployment/trading-service
        kubectl rollout status deployment/wallet-service
